### PR TITLE
ZeroFox: Bugfix - Fix version Consistency

### PR DESCRIPTION
**Pull request by DNRRomero**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [x] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by spopat-crest** [comment]
Hello @DNRRomero, Updating the app version from 1.0.1 to 3.5.1 (without other changes) will confuse the existing customers as all the versions in between are missing. 

App version has 3 parts: <_major_version_>.<_minor_version_>.<_build_version_>

1. Build version update: In case of some minor fixes(which includes but not limited to document update, typos, library update)
2. Minor version update: In case of bugfixes
3. Major version update: In case of some major changes (which includes but not limited to backward compatiblity break, API update, addition of major functionalities not currently supported by app)

As a best practice we would recommend not to upgrade app version.

cc: @nastorSplunk @junlinl-splunk @ishans-crest

**Comment by dnrr-dev** [comment]
Hi @spopat-crest 
The reason for the version-update change is that there is an existing manually distributed version of this app that has version 3.5.0, and customers are already confused about the Splunkbase app being 1.0.1.
There are no customers that we are aware of that are using the Splunkbase version of our app because of this, we have discussed this as well with Splunk SOAR's PM

**Comment by spopat-crest** [comment]
Thanks @DNRRomero We will proceed with version change.

**Comment by mishalp-crest** [comment]
@DNRRomero Can you update the release notes and give me write access?

**Comment by dnrr-dev** [comment]
Hi @mishalp-crest I've just updated the release notes. Regarding write access, do you mean write access in our forked repository?
Why is that required?

**Comment by mishalp-crest** [comment]
@DNRRomero Yes, to do cosmetic standard dev check changes if needed
kindly add the note in unreleased.md 

Also as per my observation, the expectation from your side is to delete the 1.0.1 version 
so if that is the case let us know

**Comment by dnrr-dev** [comment]
Hi @mishalp-crest  moved release notes to unreleased, also gave you write access

**Comment by dnrr-dev** [comment]
Also @mishalp-crest  yes, the only 3.5.1 version should show up in splunkbase

**Comment by mishalp-crest** [comment]
@DNRRomero I have made some changes 
let me know if you have any concerns

**Comment by dnrr-dev** [comment]
@mishalp-crest,  looks good to me

**Comment by dnrr-dev** [comment]
Hi @mishalp-crest  is there anything left you'd like to change?
is there an estimate time between PR merge and the update showing in splunkbase?

**Review by dhwanis-crest — APPROVED** [review]

**Comment by mishalp-crest** [comment]
> Hi @mishalp-crest is there anything left you'd like to change? is there an estimate time between PR merge and the update showing in splunkbase?


No, we are good.
After merging into the main it will be reflected on Splunkbase
We have to raise the request to remove the older version externally

It should get merged in main in 1 - 2 days
Not sure about the external request

**Pull request merged**
